name: NEXT STEPS
favicon: null
layout_spectrum: 0
typography_spectrum: 0.13636
title: NEXT STEPS
description: A Path to an Improved You
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee7e6'
    - '#b3b5aa'
    - '#c90a02'
    - '#050c24'
    - '#838a92'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
