typography_spectrum: 0.13636
color:
  brandColors:
    - '#dee7e6'
    - '#b3b5aa'
    - '#c90a02'
    - '#050c24'
    - '#838a92'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75654
analytics:
  google: null
  facebook: null
  twitter: null
name: NEXT STEPS
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: NEXT STEPS
description: A Path to an Improved You
purpose: []
